[project]
name = "mcp-apps-learning"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "mcp[cli]==2.2.0",
]

[project.scripts]
mcp-apps = "mcp_apps_learning.cli:main"

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "mcp_apps_learning"
module-root = ""
